maintainer       "Clinton Wolfe"
maintainer_email "clintoncwolfeNO.SPAM@gmail.com"
license          "Modified BSD"
description      "Test fixture cookbook for xml_Edit, for use with test-kitchen"
long_description "See above"
version          "0.0.1"
name             "xml_edit_test"
